# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1396, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(29, 30, 741, 561))
        self.graphWidget.setObjectName("graphWidget")
        self.buy_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.buy_tableWidget.setGeometry(QtCore.QRect(790, 30, 271, 561))
        self.buy_tableWidget.setObjectName("buy_tableWidget")
        self.buy_tableWidget.setColumnCount(2)
        self.buy_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.buy_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.buy_tableWidget.setHorizontalHeaderItem(1, item)
        self.buy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.buy_btn.setGeometry(QtCore.QRect(320, 700, 91, 41))
        self.buy_btn.setObjectName("buy_btn")
        self.buy_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.buy_input.setGeometry(QtCore.QRect(160, 700, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.buy_input.setFont(font)
        self.buy_input.setObjectName("buy_input")
        self.buy_label = QtWidgets.QLabel(self.centralwidget)
        self.buy_label.setGeometry(QtCore.QRect(160, 650, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.buy_label.setFont(font)
        self.buy_label.setObjectName("buy_label")
        self.sell_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sell_input.setGeometry(QtCore.QRect(610, 700, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.sell_input.setFont(font)
        self.sell_input.setObjectName("sell_input")
        self.sell_label = QtWidgets.QLabel(self.centralwidget)
        self.sell_label.setGeometry(QtCore.QRect(610, 650, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.sell_label.setFont(font)
        self.sell_label.setObjectName("sell_label")
        self.sell_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sell_btn.setGeometry(QtCore.QRect(770, 700, 91, 41))
        self.sell_btn.setObjectName("sell_btn")
        self.sell_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.sell_tableWidget.setGeometry(QtCore.QRect(1090, 30, 271, 561))
        self.sell_tableWidget.setObjectName("sell_tableWidget")
        self.sell_tableWidget.setColumnCount(2)
        self.sell_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sell_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sell_tableWidget.setHorizontalHeaderItem(1, item)
        self.log_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.log_listWidget.setGeometry(QtCore.QRect(920, 650, 401, 131))
        self.log_listWidget.setObjectName("log_listWidget")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(920, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.log_label.setFont(font)
        self.log_label.setObjectName("log_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1396, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock"))
        item = self.buy_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "買"))
        item = self.buy_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "價格"))
        self.buy_btn.setText(_translate("MainWindow", "確定"))
        self.buy_label.setText(_translate("MainWindow", "我要買"))
        self.sell_label.setText(_translate("MainWindow", "我要賣"))
        self.sell_btn.setText(_translate("MainWindow", "確定"))
        item = self.sell_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "賣"))
        item = self.sell_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "價格"))
        self.log_label.setText(_translate("MainWindow", "訊息"))
from pyqtgraph import PlotWidget
